language: python
python:
  - "2.7"
  - "3.2"

# install recent git version, and make sure the git config
# contains suitable default
before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:pdoes/ppa
  - sudo apt-get install -qq git
  - git config --global user.email you@example.com
  - git config --global user.name Gitifyhg
  - git config --global push.default simple

# install dependencies and gitifyhg itself;
# py.test is already preinstalled
install:
  - "pip install -q path.py>=2.5"
  - "pip install -q https://www.mercurial-scm.org/release/mercurial-$HG_VERSION.tar.gz"
  - "python setup.py -q install"

# specify various mercurial versions to test against
#
# TODO: Also test against multiple git versions;
# this may require setting up a custom PPA with suitable
# .deb's in it.
#
# NOTE: Right now, hg versions 1.8.x and older are not supported,
# due to problems with the bookmarks extension. We may or
# may not add support for them in the future, see issue #20.
env:
  - HG_VERSION=2.5
  - HG_VERSION=2.6
  - HG_VERSION=2.8 
  - HG_VERSION=3.0
  - HG_VERSION=3.5
  - HG_VERSION=4.0
  - HG_VERSION=4.0.1


# command to run actual tests
# We also output the git and hg versions to make sure we are using
# the right ones.
# Also, switch the traceback format to 'short' to work around
# a bug in py.test <= 2.3.4.
script:
  - git --version
  - hg --version
  - cd test
  - make
